# Generated by Django 4.2 on 2025-05-30 02:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('shop', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=False)),
                ('picture', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
